#! /bin/sh
### BEGIN INIT INFO
# Provides:          lernstick-final-backup
# Required-Start:    $local_fs
# Required-Stop:     $local_fs
# Default-Start:
# Default-Stop:      0 1 6
# Short-Description: Lernstick final backup
# Description:       Executes a final backup before shutdown or restart
### END INIT INFO

# Author: Ronny Standtke <ronny.standtke@gmx.net>

DESC="lernstick-final-backup"
SCRIPTNAME=/etc/init.d/$NAME

case "$1" in
  stop)
	lernstick_backup once
	;;
  *)
	echo "Usage: $SCRIPTNAME stop" >&2
	exit 3
	;;
esac
